const actionsTypesMyProject={
    LOADING_SUCCESS_MY_PROJECTS: "LOADING_SUCCESS_MY_PROJECTS",
    LOAD_SUCCESS_MY_PROJECTS: "LOAD_SUCCESS_MY_PROJECTS",
    LOAD_FAILURE_MY_PROJECTS: "LOAD_FAILURE_MY_PROJECTS",
    DELETE_SUCCESS: "DELETE_SUCCESS"
}

export default actionsTypesMyProject
